services:
  web:
    build: .
    ports:
      - "8080:80"
    restart: always
    links:
      - db
    depends_on:
      - db
  db:
    image: biarms/mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wikifab
      MYSQL_DATABASE: wikifab
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./__initdb:/docker-entrypoint-initdb.d
volumes:
  images:
  db: